# PyTorch Fundamentals

## Importing modules

In [1]:
import torch
print(torch.__version__)

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

2.1.2+cpu


## What is Tensor

In PyTorch, a tensor is a multi-dimensional array that serves as the fundamental data structure for all computations in the library. Tensors are similar to NumPy arrays but come with additional capabilities such as GPU acceleration and support for automatic differentiation, which are crucial for deep learning applications.

## Creating Tensors

### Scalar
* A scalar is a single number.
* Zero dimensional tensor.

In [2]:
s = torch.tensor(5)
s

tensor(5)

Check dimensions using `ndim` attribute

In [3]:
s.ndim

0

Retrive the number using `item()` method. 
Only works with one dimensional tensors.

In [4]:
s.item()

5

### Vector
* Single dimension tensor.
* Can contain many numbers.

In [5]:
v = torch.tensor([2, 3])
v

tensor([2, 3])

In [6]:
v.ndim

1

In [7]:
v[0].item()

2

`shape` attribute tells how the elements inside tensors are arranged.

In [8]:
v.shape

torch.Size([2])

### Matrix
* A 2-dimensional tensor.
* An array of numbers arranged in rows and columns.

In [9]:
M = torch.tensor([[10, 22],
                  [34, 50]])
M

tensor([[10, 22],
        [34, 50]])

In [10]:
M.ndim, M.shape

(2, torch.Size([2, 2]))

In [11]:
M[0, 1].item()

22

### Tensor
* A multi-dimensional matrix containing elements of a single data type.

In [12]:
T = torch.tensor([[[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]]])
T

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [13]:
T.ndim, T.shape

(3, torch.Size([1, 3, 3]))

Get total number of elements in a Tensor using `numel()` method

In [14]:
T.numel()

9

### Random tensors

a machine learning model often starts out with large random tensors of numbers and adjusts these random numbers as it works through data to better represent it.

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers...`

**Using `torch.rand()`**

Generates a tensor with random numbers from a uniform distribution on the interval [0,1)[0,1).

In [15]:
random_tensor = torch.rand(size=(4, 3))
random_tensor, random_tensor.dtype, random_tensor.shape, random_tensor.ndim, random_tensor.numel()

(tensor([[0.5925, 0.2856, 0.9801],
         [0.2432, 0.9824, 0.4287],
         [0.7564, 0.6446, 0.3488],
         [0.3756, 0.0541, 0.9302]]),
 torch.float32,
 torch.Size([4, 3]),
 2,
 12)

In [16]:
random_tensor = torch.rand(3, 3, 3)
random_tensor, random_tensor.dtype, random_tensor.shape, random_tensor.ndim, random_tensor.numel()

(tensor([[[0.2266, 0.4719, 0.0619],
          [0.8255, 0.3306, 0.8324],
          [0.8875, 0.9067, 0.9460]],
 
         [[0.2500, 0.2935, 0.9938],
          [0.4643, 0.3491, 0.2353],
          [0.1481, 0.8508, 0.6950]],
 
         [[0.8834, 0.0684, 0.5735],
          [0.8009, 0.4483, 0.1325],
          [0.5075, 0.0654, 0.1840]]]),
 torch.float32,
 torch.Size([3, 3, 3]),
 3,
 27)

**Using `torch.randn()`**

Generates a tensor with random numbers from a normal (Gaussian) distribution with mean 0 and standard deviation 1.

In [17]:
random_tensor = torch.randn(2, 2, 3)
random_tensor, random_tensor.dtype, random_tensor.shape, random_tensor.ndim, random_tensor.numel()

(tensor([[[-2.7726, -0.8636, -1.2546],
          [-2.1268,  0.0745, -0.7416]],
 
         [[-0.1709, -0.3166, -0.2486],
          [ 0.4372,  0.7788, -1.0597]]]),
 torch.float32,
 torch.Size([2, 2, 3]),
 3,
 12)

**Using `torch.randint()`**

Generates a tensor with random integers from a specified range.

In [18]:
random_tensor = torch.randint(10, 40, (2, 2, 2))
random_tensor, random_tensor.dtype, random_tensor.shape, random_tensor.ndim, random_tensor.numel()

(tensor([[[28, 21],
          [21, 15]],
 
         [[30, 29],
          [17, 24]]]),
 torch.int64,
 torch.Size([2, 2, 2]),
 3,
 8)

**Using `torch.randperm()`**

Generates a tensor with a random permutation of integers from 0 to n−1.