# PyTorch Fundamentals

## Importing modules

In [1]:
import random

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import torch
torch.__version__

'2.3.1'

## What is Tensor

In PyTorch, a tensor is a multidimensional array that serves as the fundamental data structure for all computations in the library. Tensors are similar to NumPy arrays but come with additional capabilities such as GPU acceleration and support for automatic differentiation, which are crucial for deep learning applications.

## Creating Tensors

### Scalar
* A scalar is a single number.
* Zero dimensional tensor.

In [2]:
s = torch.tensor(5)
s

tensor(5)

Check dimensions using `ndim` attribute

In [3]:
s.ndim

0

Retrieve the number using `item()` method. 
Only works with one dimensional tensors.

In [4]:
s.item()

5

### Vector
* Single dimension tensor.
* Can contain many numbers.

In [5]:
v = torch.tensor([2, 3])
v

tensor([2, 3])

In [6]:
v.ndim

1

In [7]:
v[0].item()

2

`shape` attribute tells how the elements inside tensors are arranged.

In [8]:
v.shape

torch.Size([2])

### Matrix
* A 2-dimensional tensor.
* An array of numbers arranged in rows and columns.

In [9]:
M = torch.tensor([[10, 22],
                  [34, 50]])
M

tensor([[10, 22],
        [34, 50]])

In [10]:
M.ndim, M.shape

(2, torch.Size([2, 2]))

In [11]:
M[0, 1].item()

22

### Tensor
* A multi-dimensional matrix containing elements of a single data type.

In [12]:
T = torch.tensor([[[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]]])
T

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [13]:
T.ndim, T.shape

(3, torch.Size([1, 3, 3]))

Get total number of elements in a Tensor using `numel()` method

In [14]:
T.numel()

9

### Random tensors

a machine learning model often starts out with large random tensors of numbers and adjusts these random numbers as it works through data to better represent it.

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers...`

**Using `torch.rand()`**

Generates a tensor with random numbers from a uniform distribution on the interval [0,1)[0,1).

In [15]:
random_tensor = torch.rand(size=(4, 3))
random_tensor, random_tensor.dtype, random_tensor.shape, random_tensor.ndim, random_tensor.numel()

(tensor([[0.5741, 0.5827, 0.5953],
         [0.3639, 0.5326, 0.1497],
         [0.6629, 0.0272, 0.1596],
         [0.8198, 0.2494, 0.4252]]),
 torch.float32,
 torch.Size([4, 3]),
 2,
 12)

In [16]:
random_tensor = torch.rand(3, 3, 3)
random_tensor, random_tensor.dtype, random_tensor.shape, random_tensor.ndim, random_tensor.numel()

(tensor([[[0.5712, 0.6661, 0.2700],
          [0.7077, 0.5706, 0.1819],
          [0.3660, 0.7687, 0.3669]],
 
         [[0.3514, 0.2252, 0.6540],
          [0.4845, 0.3753, 0.9952],
          [0.0903, 0.5902, 0.0852]],
 
         [[0.6479, 0.8204, 0.4826],
          [0.3902, 0.4172, 0.6300],
          [0.7308, 0.2875, 0.4991]]]),
 torch.float32,
 torch.Size([3, 3, 3]),
 3,
 27)

**Using `torch.randn()`**

Generates a tensor with random numbers from a normal (Gaussian) distribution with mean 0 and standard deviation 1.

In [17]:
random_tensor = torch.randn(2, 2, 3)
random_tensor, random_tensor.dtype, random_tensor.shape, random_tensor.ndim, random_tensor.numel()

(tensor([[[-0.6172, -0.0090,  0.3714],
          [-0.6140,  0.1251, -0.4663]],
 
         [[ 1.0362, -0.0599, -0.2902],
          [-0.1940, -0.7392,  1.5202]]]),
 torch.float32,
 torch.Size([2, 2, 3]),
 3,
 12)

**Using `torch.randint()`**

Generates a tensor with random integers from a specified range.

In [18]:
random_tensor = torch.randint(10, 40, (2, 2, 2))
random_tensor, random_tensor.dtype, random_tensor.shape, random_tensor.ndim, random_tensor.numel()

(tensor([[[19, 21],
          [22, 32]],
 
         [[24, 10],
          [19, 16]]]),
 torch.int64,
 torch.Size([2, 2, 2]),
 3,
 8)

**Using `torch.randperm()`**

Generates a tensor with a random permutation of integers from 0 to n−1.

In [19]:
random_tensor = torch.randperm(20)
random_tensor, random_tensor.dtype, random_tensor.shape, random_tensor.ndim, random_tensor.numel()

(tensor([10, 19, 13,  2,  7,  3,  0, 17,  1,  9, 15, 12, 14,  5, 11,  8, 18, 16,
          6,  4]),
 torch.int64,
 torch.Size([20]),
 1,
 20)

### Zeros
Create a tensor fill with zeros using `torch.zeros()`.

In [20]:
zeros = torch.zeros(size=(2, 4))
zeros, zeros.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

In [21]:
zeros = torch.zeros(3, 3)
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

### Ones
Create a tensor fill with ones using `torch.ones()`.

In [22]:
ones = torch.ones(size=(2, 2))
ones, ones.dtype

(tensor([[1., 1.],
         [1., 1.]]),
 torch.float32)

In [23]:
ones = torch.ones(2, 3, 2)
ones

tensor([[[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]]])

### Ranged
Create tensors with a range of numbers using `torch.arange(start, end, step)`.

In [24]:
zero_to_twenty = torch.arange(0, 20, 1)
zero_to_twenty

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19])

In [25]:
zero_to_hundred = torch.arange(0, 100, 5)
zero_to_hundred

tensor([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85,
        90, 95])

### Tensors like
Create a certain type of tensor with the same shape of another.

In [26]:
random_tensor = torch.rand(3, 3)
random_tensor

tensor([[0.6293, 0.2149, 0.6536],
        [0.6380, 0.7510, 0.5809],
        [0.2114, 0.3197, 0.9507]])

**Using `torch.zeros_like(input)`**

In [27]:
random_tensor_like = torch.zeros_like(random_tensor)
random_tensor_like

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

**Using `torch.ones_like(input)`**

In [28]:
random_tensor_like = torch.ones_like(random_tensor)
random_tensor_like

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

## Tensor Manipulation

**Operations:**
- Addition
- Subtraction
- Multiplication
- Division
- Matrix multiplication

### Basic operations

In [29]:
# addition
tensor = torch.tensor([10, 20, 30])
tensor + 10

tensor([20, 30, 40])

In [30]:
# multiplication
tensor * 10

tensor([100, 200, 300])

In [31]:
# subtraction
tensor - 10

tensor([ 0, 10, 20])

Using `torch.add()` to perform addition

In [32]:
torch.add(tensor, 10)

tensor([20, 30, 40])

Using `torch.mul()` to perform multiplication

In [33]:
torch.mul(tensor, 10), torch.multiply(tensor, 10)

(tensor([100, 200, 300]), tensor([100, 200, 300]))

### Matrix multiplication

**Rules:**
- The **_inner dimensions_** must match.
- The resulting matrix has the shape of the **_outer dimensions_**.

"`@`" symbol is used for matrix multiplication in Python.

In [34]:
tensor = torch.tensor([10, 20, 30])
tensor.shape

torch.Size([3])

In [35]:
# Element-wise matrix multiplication
tensor * tensor

tensor([100, 400, 900])

In [36]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(1400)

In [37]:
tensor @ tensor

tensor(1400)

In [38]:
tensor = torch.tensor([[1, 2], [3, 4]])
torch.matmul(tensor, tensor)

tensor([[ 7, 10],
        [15, 22]])

In [39]:
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])
tensor_B = torch.tensor([[7, 8],
                         [9, 10],
                         [11, 12]])

tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

In [40]:
# transposing tensor_B for matrix multiplication
tensor_B = tensor_B.T

torch.matmul(tensor_A, tensor_B)

tensor([[ 23,  29,  35],
        [ 53,  67,  81],
        [ 83, 105, 127]])