# PyTorch Fundamentals

## Importing modules

In [1]:
import random

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import torch
torch.__version__

'2.3.1'

## What is Tensor

In PyTorch, a tensor is a multidimensional array that serves as the fundamental data structure for all computations in the library. Tensors are similar to NumPy arrays but come with additional capabilities such as GPU acceleration and support for automatic differentiation, which are crucial for deep learning applications.

## Creating Tensors

### Scalar
* A scalar is a single number.
* Zero dimensional tensor.

In [2]:
s = torch.tensor(5)
s

tensor(5)

Check dimensions using `ndim` attribute

In [3]:
s.ndim

0

Retrieve the number using `item()` method. 
Only works with one dimensional tensors.

In [4]:
s.item()

5

### Vector
* Single dimension tensor.
* Can contain many numbers.

In [5]:
v = torch.tensor([2, 3])
v

tensor([2, 3])

In [6]:
v.ndim

1

In [7]:
v[0].item()

2

`shape` attribute tells how the elements inside tensors are arranged.

In [8]:
v.shape

torch.Size([2])

### Matrix
* A 2-dimensional tensor.
* An array of numbers arranged in rows and columns.

In [9]:
M = torch.tensor([[10, 22],
                  [34, 50]])
M

tensor([[10, 22],
        [34, 50]])

In [10]:
M.ndim, M.shape

(2, torch.Size([2, 2]))

In [11]:
M[0, 1].item()

22

### Tensor
* A multi-dimensional matrix containing elements of a single data type.

In [12]:
T = torch.tensor([[[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]]])
T

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [13]:
T.ndim, T.shape

(3, torch.Size([1, 3, 3]))

Get total number of elements in a Tensor using `numel()` method

In [14]:
T.numel()

9

### Random tensors

a machine learning model often starts out with large random tensors of numbers and adjusts these random numbers as it works through data to better represent it.

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers...`

**Using `torch.rand()`**

Generates a tensor with random numbers from a uniform distribution on the interval [0,1)[0,1).

In [15]:
torch.manual_seed(10)
random_tensor = torch.rand(size=(4, 3))
random_tensor, random_tensor.dtype, random_tensor.shape, random_tensor.ndim, random_tensor.numel()

(tensor([[0.4581, 0.4829, 0.3125],
         [0.6150, 0.2139, 0.4118],
         [0.6938, 0.9693, 0.6178],
         [0.3304, 0.5479, 0.4440]]),
 torch.float32,
 torch.Size([4, 3]),
 2,
 12)

In [16]:
torch.manual_seed(20)
random_tensor = torch.rand(3, 3, 3)
random_tensor, random_tensor.dtype, random_tensor.shape, random_tensor.ndim, random_tensor.numel()

(tensor([[[0.5615, 0.1774, 0.8147],
          [0.3295, 0.2319, 0.7832],
          [0.8544, 0.1012, 0.1877]],
 
         [[0.9310, 0.0899, 0.3156],
          [0.9423, 0.2536, 0.7388],
          [0.5404, 0.4356, 0.4430]],
 
         [[0.6257, 0.0379, 0.7130],
          [0.3229, 0.9631, 0.2284],
          [0.4489, 0.2113, 0.6839]]]),
 torch.float32,
 torch.Size([3, 3, 3]),
 3,
 27)

**Using `torch.randn()`**

Generates a tensor with random numbers from a normal (Gaussian) distribution with mean 0 and standard deviation 1.

In [17]:
torch.manual_seed(30)
random_tensor = torch.randn(2, 2, 3)
random_tensor, random_tensor.dtype, random_tensor.shape, random_tensor.ndim, random_tensor.numel()

(tensor([[[ 0.4705,  1.6563,  0.5153],
          [-0.2744, -2.2606,  1.2280]],
 
         [[ 0.7928,  0.6231, -2.1520],
          [-0.0252,  0.9949,  0.0494]]]),
 torch.float32,
 torch.Size([2, 2, 3]),
 3,
 12)

**Using `torch.randint()`**

Generates a tensor with random integers from a specified range.

In [18]:
torch.manual_seed(40)
random_tensor = torch.randint(10, 40, (2, 2, 2))
random_tensor, random_tensor.dtype, random_tensor.shape, random_tensor.ndim, random_tensor.numel()

(tensor([[[38, 33],
          [15, 37]],
 
         [[22, 14],
          [36, 13]]]),
 torch.int64,
 torch.Size([2, 2, 2]),
 3,
 8)

**Using `torch.randperm()`**

Generates a tensor with a random permutation of integers from 0 to n−1.

In [19]:
torch.manual_seed(50)
random_tensor = torch.randperm(20)
random_tensor, random_tensor.dtype, random_tensor.shape, random_tensor.ndim, random_tensor.numel()

(tensor([ 4,  1,  3,  8,  5,  0, 18, 19, 17, 15,  6, 10,  2,  9,  7, 13, 14, 12,
         11, 16]),
 torch.int64,
 torch.Size([20]),
 1,
 20)

### Zeros
Create a tensor fill with zeros using `torch.zeros()`.

In [20]:
zeros = torch.zeros(size=(2, 4))
zeros, zeros.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

In [21]:
zeros = torch.zeros(3, 3)
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

### Ones
Create a tensor fill with ones using `torch.ones()`.

In [22]:
ones = torch.ones(size=(2, 2))
ones, ones.dtype

(tensor([[1., 1.],
         [1., 1.]]),
 torch.float32)

In [23]:
ones = torch.ones(2, 3, 2)
ones

tensor([[[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]]])

### Ranged
Create tensors with a range of numbers using `torch.arange(start, end, step)`.

In [24]:
zero_to_twenty = torch.arange(0, 20, 1)
zero_to_twenty

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19])

In [25]:
zero_to_hundred = torch.arange(0, 100, 5)
zero_to_hundred

tensor([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85,
        90, 95])

### Tensors like
Create a certain type of tensor with the same shape of another.

In [26]:
torch.manual_seed(40)
random_tensor = torch.rand(3, 3)
random_tensor

tensor([[0.3679, 0.8661, 0.1737],
        [0.7157, 0.8649, 0.4878],
        [0.5501, 0.1318, 0.2897]])

**Using `torch.zeros_like(input)`**

In [27]:
random_tensor_like = torch.zeros_like(random_tensor)
random_tensor_like

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

**Using `torch.ones_like(input)`**

In [28]:
random_tensor_like = torch.ones_like(random_tensor)
random_tensor_like

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

## Tensor Manipulation

**Operations:**
- Addition
- Subtraction
- Multiplication
- Division
- Matrix multiplication

### Basic operations

In [29]:
# addition
tensor = torch.tensor([10, 20, 30])
tensor + 10

tensor([20, 30, 40])

In [30]:
# multiplication
tensor * 10

tensor([100, 200, 300])

In [31]:
# subtraction
tensor - 10

tensor([ 0, 10, 20])

Using `torch.add()` to perform addition

In [32]:
torch.add(tensor, 10)

tensor([20, 30, 40])

Using `torch.mul()` to perform multiplication

In [33]:
torch.mul(tensor, 10), torch.multiply(tensor, 10)

(tensor([100, 200, 300]), tensor([100, 200, 300]))

### Matrix multiplication

**Rules:**
- The **_inner dimensions_** must match.
- The resulting matrix has the shape of the **_outer dimensions_**.

"`@`" symbol is used for matrix multiplication in Python.

In [34]:
tensor = torch.tensor([10, 20, 30])
tensor.shape

torch.Size([3])

In [35]:
# Element-wise matrix multiplication
tensor * tensor

tensor([100, 400, 900])

In [36]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(1400)

In [37]:
tensor @ tensor

tensor(1400)

In [38]:
tensor = torch.tensor([[1, 2], [3, 4]])
torch.matmul(tensor, tensor)

tensor([[ 7, 10],
        [15, 22]])

In [39]:
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])
tensor_B = torch.tensor([[7, 8],
                         [9, 10],
                         [11, 12]])

tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

In [40]:
# transposing tensor_B for matrix multiplication
tensor_B = tensor_B.T

torch.matmul(tensor_A, tensor_B)

tensor([[ 23,  29,  35],
        [ 53,  67,  81],
        [ 83, 105, 127]])

jflsdjalf

In [41]:
torch.manual_seed(42)

linear = torch.nn.Linear(in_features=2, out_features=6)

tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

x = tensor_A
output = linear(x)
x.shape, output, output.shape

(torch.Size([3, 2]),
 tensor([[2.2368, 1.2292, 0.4714, 0.3864, 0.1309, 0.9838],
         [4.4919, 2.1970, 0.4469, 0.5285, 0.3401, 2.4777],
         [6.7469, 3.1648, 0.4224, 0.6705, 0.5493, 3.9716]],
        grad_fn=<AddmmBackward0>),
 torch.Size([3, 6]))

## Aggregation

**Finding the min, max, mean, sum, etc.**

In [42]:
x = torch.arange(0, 100, 10)
x, x.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [43]:
# maximum
print(f'Maximum: {x.max()}')
# minimum
print(f'Minimum: {x.min()}')
# sum
print(f'Sum: {x.sum()}')
# mean
# print(f'Mean: {x.mean()}') # error # only works with float datatype
print(f'Mean: {x.type(torch.float32).mean()}')

Maximum: 90
Minimum: 0
Sum: 450
Mean: 45.0


In [44]:
torch.manual_seed(42)
x = torch.rand(3, 3)
print(x)
# maximum
print(f'Maximum: {x.max()}')
# minimum
print(f'Minimum: {x.min()}')
# sum
print(f'Sum: {x.sum()}')
# mean
print(f'Mean: {x.type(torch.float32).mean()}')

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009],
        [0.2566, 0.7936, 0.9408]])
Maximum: 0.9593056440353394
Minimum: 0.2565724849700928
Sum: 6.121770858764648
Mean: 0.6801967620849609


## Positional min/max

Finding the index of a tensor where the max(using **`torch.argmax()`**) or min(using **`torch.argmin()`**) occurs.

In [45]:
tensor = torch.arange(0., 100., 10)
print(tensor)

# index of max value
print(f'Index of max value: {tensor.argmax()}')
print(f'Index of min value: {tensor.argmin()}')

tensor([ 0., 10., 20., 30., 40., 50., 60., 70., 80., 90.])
Index of max value: 9
Index of min value: 0


In [46]:
torch.manual_seed(56)
tensor = torch.randint(0, 100, (3, 3))
print(tensor)

# index of max value
print(f'Index of max value: {tensor.argmax()}')
print(f'Index of min value: {tensor.argmin()}')

tensor([[29, 32, 67],
        [68, 34, 11],
        [26, 46, 77]])
Index of max value: 8
Index of min value: 5


## Changing tensor datatype

Using **`torch.Tensor.type(dtype=None)`**

In [47]:
torch.manual_seed(20)
# creating a tensor
tensor = torch.randint(1, 100, (2, 2))
tensor, tensor.dtype

(tensor([[ 9, 83],
         [58, 56]]),
 torch.int64)

In [48]:
# changing datatype of the tensor
tensor_float32 = tensor.type(torch.float32)
tensor_float32, tensor_float32.dtype

(tensor([[ 9., 83.],
         [58., 56.]]),
 torch.float32)

In [49]:
# changing datatype of tensor_float32
tensor_int16 = tensor_float32.type(torch.int16)
tensor_int16, tensor_int16.dtype

(tensor([[ 9, 83],
         [58, 56]], dtype=torch.int16),
 torch.int16)

## Reshaping, stacking, squeezing and unsqueezing

In [50]:
# creating a tensor
torch.manual_seed(22)
tensor = torch.randint(1, 100, (9,))
tensor, tensor.shape, tensor.ndim

(tensor([39, 53, 11, 85,  8, 84, 12, 11, 57]), torch.Size([9]), 1)

**Reshaping tensor using `torch.reshape()`**

In [51]:
# adding extra dimension
tensor_reshaped = tensor.reshape(1, 9)
tensor_reshaped, tensor_reshaped.shape, tensor_reshaped.ndim

(tensor([[39, 53, 11, 85,  8, 84, 12, 11, 57]]), torch.Size([1, 9]), 2)

In [52]:
tensor_reshaped = tensor.reshape(1, 3, 3)
tensor_reshaped, tensor_reshaped.shape, tensor_reshaped.ndim

(tensor([[[39, 53, 11],
          [85,  8, 84],
          [12, 11, 57]]]),
 torch.Size([1, 3, 3]),
 3)

Changing view using **`torch.view()`** (_keeps same data_) 

In [53]:
z = tensor.view(3, 3)
z

tensor([[39, 53, 11],
        [85,  8, 84],
        [12, 11, 57]])

In [54]:
tensor

tensor([39, 53, 11, 85,  8, 84, 12, 11, 57])

_Changing the view changes the original tensor too._

In [55]:
z[:, 0] = 500
z, tensor

(tensor([[500,  53,  11],
         [500,   8,  84],
         [500,  11,  57]]),
 tensor([500,  53,  11, 500,   8,  84, 500,  11,  57]))

**Stacking tensors using `tensor.stack()`**

In [56]:
# Stacking on top of each other
tensor_stacked = torch.stack([tensor, tensor, tensor, tensor, tensor], dim=0)
tensor_stacked

tensor([[500,  53,  11, 500,   8,  84, 500,  11,  57],
        [500,  53,  11, 500,   8,  84, 500,  11,  57],
        [500,  53,  11, 500,   8,  84, 500,  11,  57],
        [500,  53,  11, 500,   8,  84, 500,  11,  57],
        [500,  53,  11, 500,   8,  84, 500,  11,  57]])

In [57]:
# Stacking on top of each other
tensor_stacked = torch.stack([tensor, tensor, tensor, tensor, tensor], dim=1)
tensor_stacked

tensor([[500, 500, 500, 500, 500],
        [ 53,  53,  53,  53,  53],
        [ 11,  11,  11,  11,  11],
        [500, 500, 500, 500, 500],
        [  8,   8,   8,   8,   8],
        [ 84,  84,  84,  84,  84],
        [500, 500, 500, 500, 500],
        [ 11,  11,  11,  11,  11],
        [ 57,  57,  57,  57,  57]])

**Using `torch.squeeze()` and `torch.squeeze()` to squeeze tensor and reverse squeezing.**

In [58]:
tensor_reshaped, tensor_reshaped.shape

(tensor([[[500,  53,  11],
          [500,   8,  84],
          [500,  11,  57]]]),
 torch.Size([1, 3, 3]))

In [59]:
# Removing dimension from tensor_reshaped
tensor_squeezed = tensor_reshaped.squeeze()
tensor_squeezed, tensor_squeezed.shape

(tensor([[500,  53,  11],
         [500,   8,  84],
         [500,  11,  57]]),
 torch.Size([3, 3]))

In [60]:
# Adding dimension with unsqueeze
tensor_unsqueezed = tensor_squeezed.unsqueeze(dim=0)
tensor_unsqueezed, tensor_unsqueezed.shape

(tensor([[[500,  53,  11],
          [500,   8,  84],
          [500,  11,  57]]]),
 torch.Size([1, 3, 3]))

**Rearrange the order of axes values with `torch.permute(input, dims)`, where the `input`
gets turned into a view with new `dims`**

In [61]:
torch.manual_seed(52)
tensor_original = torch.rand((224, 120, 3))

tensor_permuted = tensor_original.permute(2, 0, 1)

tensor_original.shape, tensor_permuted.shape

(torch.Size([224, 120, 3]), torch.Size([3, 224, 120]))

## Indexing

Selecting data from tensors

In [62]:
tensor = torch.arange(1, 10).reshape(1, 3, 3)
tensor, tensor.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [63]:
tensor[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [64]:
tensor[0][0]

tensor([1, 2, 3])

In [65]:
tensor[0][0][0]

tensor(1)

In [66]:
# Get all values of 0th dimension and the 0 index of 1st dimension
tensor[:, 0]

tensor([[1, 2, 3]])

In [67]:
# Get all values of 0th & 1st dimension but only index 1 of 2nd dimension
tensor[:, :, 1]

tensor([[2, 5, 8]])

In [68]:
# Get all values of the 0 dimension but only the 1 index value of the 1st and 2nd dimension
tensor[:, 1, 1]

tensor([5])

In [69]:
# Get index 0 of 0th and 1st dimension and all values of 2nd dimension
tensor[0, 0, :]

tensor([1, 2, 3])

## PyTorch tensors and Numpy

- `torch.from_numpy(ndarray)` - NumPy array -> PyTorch tensor
- `torch.Tensor.numpy()` - PyTorch tensor -> NumPy array

In [70]:
np_array = np.arange(0., 9.)
tensor = torch.from_numpy(np_array)
float32_tensor = torch.from_numpy(np_array).type(torch.float32)
np_array, tensor, (float32_tensor, float32_tensor.dtype)

(array([0., 1., 2., 3., 4., 5., 6., 7., 8.]),
 tensor([0., 1., 2., 3., 4., 5., 6., 7., 8.], dtype=torch.float64),
 (tensor([0., 1., 2., 3., 4., 5., 6., 7., 8.]), torch.float32))

In [71]:
tensor = torch.zeros(9)
numpy_array = tensor.numpy()
tensor, numpy_array

(tensor([0., 0., 0., 0., 0., 0., 0., 0., 0.]),
 array([0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32))