# PyTorch Fundamentals

## Importing modules

In [1]:
import torch
print(torch.__version__)

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

2.3.0


## What is Tensor

In PyTorch, a tensor is a multidimensional array that serves as the fundamental data structure for all computations in the library. Tensors are similar to NumPy arrays but come with additional capabilities such as GPU acceleration and support for automatic differentiation, which are crucial for deep learning applications.

## Creating Tensors

### Scalar
* A scalar is a single number.
* Zero dimensional tensor.

In [2]:
s = torch.tensor(5)
s

tensor(5)

Check dimensions using `ndim` attribute

In [3]:
s.ndim

0

Retrieve the number using `item()` method. 
Only works with one dimensional tensors.

In [4]:
s.item()

5

### Vector
* Single dimension tensor.
* Can contain many numbers.

In [5]:
v = torch.tensor([2, 3])
v

tensor([2, 3])

In [6]:
v.ndim

1

In [7]:
v[0].item()

2

`shape` attribute tells how the elements inside tensors are arranged.

In [8]:
v.shape

torch.Size([2])

### Matrix
* A 2-dimensional tensor.
* An array of numbers arranged in rows and columns.

In [9]:
M = torch.tensor([[10, 22],
                  [34, 50]])
M

tensor([[10, 22],
        [34, 50]])

In [10]:
M.ndim, M.shape

(2, torch.Size([2, 2]))

In [11]:
M[0, 1].item()

22

### Tensor
* A multi-dimensional matrix containing elements of a single data type.

In [12]:
T = torch.tensor([[[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]]])
T

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [13]:
T.ndim, T.shape

(3, torch.Size([1, 3, 3]))

Get total number of elements in a Tensor using `numel()` method

In [14]:
T.numel()

9

### Random tensors

a machine learning model often starts out with large random tensors of numbers and adjusts these random numbers as it works through data to better represent it.

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers...`

**Using `torch.rand()`**

Generates a tensor with random numbers from a uniform distribution on the interval [0,1)[0,1).

In [15]:
random_tensor = torch.rand(size=(4, 3))
random_tensor, random_tensor.dtype, random_tensor.shape, random_tensor.ndim, random_tensor.numel()

(tensor([[0.8035, 0.9702, 0.8934],
         [0.8268, 0.2575, 0.6248],
         [0.8717, 0.1657, 0.6435],
         [0.7357, 0.1506, 0.8015]]),
 torch.float32,
 torch.Size([4, 3]),
 2,
 12)

In [16]:
random_tensor = torch.rand(3, 3, 3)
random_tensor, random_tensor.dtype, random_tensor.shape, random_tensor.ndim, random_tensor.numel()

(tensor([[[9.1376e-01, 9.3384e-02, 2.3753e-01],
          [5.3460e-01, 2.7414e-01, 3.4782e-02],
          [8.4110e-01, 6.9130e-01, 9.3299e-04]],
 
         [[3.6356e-01, 4.3767e-01, 1.1792e-01],
          [4.9106e-01, 7.7474e-03, 5.8303e-01],
          [8.1865e-01, 2.7395e-01, 9.8985e-01]],
 
         [[3.8550e-01, 9.2475e-01, 6.3629e-01],
          [7.5944e-01, 5.4580e-01, 6.9375e-02],
          [1.7408e-02, 9.2358e-01, 2.4747e-01]]]),
 torch.float32,
 torch.Size([3, 3, 3]),
 3,
 27)

**Using `torch.randn()`**

Generates a tensor with random numbers from a normal (Gaussian) distribution with mean 0 and standard deviation 1.

In [17]:
random_tensor = torch.randn(2, 2, 3)
random_tensor, random_tensor.dtype, random_tensor.shape, random_tensor.ndim, random_tensor.numel()

(tensor([[[ 0.1146,  0.2651,  1.6692],
          [-1.0147,  1.2716,  0.1383]],
 
         [[-1.8516, -0.7065, -1.0121],
          [-0.0522, -1.6044,  1.7198]]]),
 torch.float32,
 torch.Size([2, 2, 3]),
 3,
 12)

**Using `torch.randint()`**

Generates a tensor with random integers from a specified range.

In [18]:
random_tensor = torch.randint(10, 40, (2, 2, 2))
random_tensor, random_tensor.dtype, random_tensor.shape, random_tensor.ndim, random_tensor.numel()

(tensor([[[21, 22],
          [32, 16]],
 
         [[24, 34],
          [33, 18]]]),
 torch.int64,
 torch.Size([2, 2, 2]),
 3,
 8)

**Using `torch.randperm()`**

Generates a tensor with a random permutation of integers from 0 to n−1.

In [19]:
random_tensor = torch.randperm(20)
random_tensor, random_tensor.dtype, random_tensor.shape, random_tensor.ndim, random_tensor.numel()

(tensor([19, 16, 11, 18,  1,  6,  0,  2, 10,  7,  4, 13,  3,  5,  8, 12, 17, 15,
         14,  9]),
 torch.int64,
 torch.Size([20]),
 1,
 20)

### Zeros
Create a tensor fill with zeros using `torch.zeros()`.

In [20]:
zeros = torch.zeros(size=(2, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [21]:
zeros = torch.zeros(3, 3)
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

### Ones
Create a tensor fill with ones using `torch.ones()`.

In [22]:
ones = torch.ones(size=(2, 2))
ones

tensor([[1., 1.],
        [1., 1.]])

In [23]:
ones = torch.ones(2, 3)
ones

tensor([[1., 1., 1.],
        [1., 1., 1.]])

### Ranged
Create tensors with a range of numbers using `torch.arange(start, end, step)`.

In [24]:
zero_to_twenty = torch.arange(0, 20, 1)
zero_to_twenty

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19])

In [25]:
zero_to_hundred = torch.arange(0, 100, 5)
zero_to_hundred

tensor([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85,
        90, 95])

### Tensors like
Create a certain type of tensor with the same shape of another.

In [26]:
random_tensor = torch.rand(3, 3)
random_tensor

tensor([[0.3504, 0.4989, 0.1044],
        [0.9009, 0.9330, 0.3265],
        [0.0902, 0.6053, 0.7802]])

**Using `torch.zeros_like(input)`**

In [27]:
random_tensor_like = torch.zeros_like(random_tensor)
random_tensor_like

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

**Using `torch.ones_like(input)`**

In [28]:
random_tensor_like = torch.ones_like(random_tensor)
random_tensor_like

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])