# Numpy Basics

## Installing Numpy

In [1]:
# using pip3
! pip3 install numpy

## Importing Numpy

In [2]:
import numpy as np
np.__version__

'1.26.4'

## Numpy Array Restrictions

- All elements of the array must be of the same type of data.
- Once created, the total size of the array can’t change.
- The shape must be “rectangular”, not “jagged”; e.g., each row of a two-dimensional array must have the same number of columns.

## Creating Numpy Arrays

In [3]:
# 1D Array
a = np.array([1, 2, 3])
print(a)
# 2D Array
b = np.array([[1, 2, 3], [4, 5, 6]])
print(b)
# 3D Array
c = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(c)

[1 2 3]
[[1 2 3]
 [4 5 6]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


### Creating Numpy Arrays with specific data types

In [4]:
a = np.array([1, 2, 3])
b = np.array([3.0, 4.0, 5.0])
print(a.dtype)
print(b.dtype)

int64
float64


In [5]:
a = np.array([1, 2, 3], dtype='int16')
print(a)
print(a.dtype)

[1 2 3]
int16


In [6]:
a = np.array([1, 2, 3], dtype='float32')
print(a)
print(a.dtype)

[1. 2. 3.]
float32


### Using `np.zeros()`
create an array filled with zeros.

In [7]:
a = np.zeros(10)
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [8]:
s = (3, 3)
b = np.zeros(s)
print(b)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


### Using `np.ones()`
create an array filled with ones.

In [9]:
a = np.ones(5)
print(a)
b = np.ones(3, dtype='int64')
print(b)

[1. 1. 1. 1. 1.]
[1 1 1]


In [10]:
a = np.ones((5, 5))
print(a)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [11]:
a = np.ones((3, 3)) * 5
print(a)

[[5. 5. 5.]
 [5. 5. 5.]
 [5. 5. 5.]]


### Using `np.empty()`

create an array of a specified shape without initializing its elements. Unlike `np.zeros()` which initializes all elements to zeros, `np.empty()` does not initialize the elements at all. Instead, it allocates the memory needed for the array but does not set the values of the elements. The values of the array will be whatever happens to already exist at that memory location.

In [12]:
a = np.empty(5)
print(a)

[1. 1. 1. 1. 1.]


In [13]:
b = np.empty((4, 4))
print(b)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


### Using `np.arange()`
create arrays with regularly spaced values within a specified interval. It is similar to Python's built-in `range()` function but returns an array instead of a list.

In [14]:
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [15]:
b = np.arange(10, 20)
print(b)

[10 11 12 13 14 15 16 17 18 19]


In [16]:
c = np.arange(30, 60, 2)
print(c)

[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58]


### Using `np.linspace()`
create arrays with evenly spaced numbers over a specified interval. Unlike `np.arange()`, which generates values with a specified step size, `np.linspace()` generates values that are evenly spaced between the specified start and stop values, inclusive by default.

In [17]:
a = np.linspace(10, 20)
print(a)

[10.         10.20408163 10.40816327 10.6122449  10.81632653 11.02040816
 11.2244898  11.42857143 11.63265306 11.83673469 12.04081633 12.24489796
 12.44897959 12.65306122 12.85714286 13.06122449 13.26530612 13.46938776
 13.67346939 13.87755102 14.08163265 14.28571429 14.48979592 14.69387755
 14.89795918 15.10204082 15.30612245 15.51020408 15.71428571 15.91836735
 16.12244898 16.32653061 16.53061224 16.73469388 16.93877551 17.14285714
 17.34693878 17.55102041 17.75510204 17.95918367 18.16326531 18.36734694
 18.57142857 18.7755102  18.97959184 19.18367347 19.3877551  19.59183673
 19.79591837 20.        ]


In [18]:
b = np.linspace(0, 100, num=10) # default num = 50
print(b)

[  0.          11.11111111  22.22222222  33.33333333  44.44444444
  55.55555556  66.66666667  77.77777778  88.88888889 100.        ]


In [19]:
c = np.linspace(10, 20, 5)
print(c)

[10.  12.5 15.  17.5 20. ]


### using `np.eye()`

create a 2-D array with ones on the diagonal and zeros elsewhere.
Similar to `np.identity()`.

In [20]:
a = np.eye(3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [21]:
# parameters: (rows in output, cols in output, index of the diagonal: 0 default)
b = np.eye(3, 3, 1)
print(b)
c = np.eye(3, 3, -1)
print(c)

[[0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]]


## Array attributes

In [22]:
# 1D Array
a = np.array([1, 2, 3, 4, 5])
# 2D Array
b = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
# 3D Array
c = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print('a=', a, 'b=', b, 'c=', c, sep='\n')

a=
[1 2 3 4 5]
b=
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
c=
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


### `ndim`
Attribute contains the number of dimensions of an array.

In [23]:
print(a.ndim)
print(b.ndim)
print(c.ndim)

1
2
3


### `shape`
- Specify the number of elements along each dimension.
- a tuple of non-negative integers

In [24]:
print('shape of a=', a.shape)
print('shape of b=', b.shape)
print('shape of c=', c.shape)

shape of a= (5,)
shape of b= (2, 5)
shape of c= (2, 2, 3)


In [25]:
# len(ndarray.shape) == ndarray.dim -> True
print('len of a.shape:', len(a.shape), 'dim of a:', a.ndim)
print('len of b.shape:', len(b.shape), 'dim of b:', b.ndim)
print('len of c.shape:', len(c.shape), 'dim of c:', c.ndim)

len of a.shape: 1 dim of a: 1
len of b.shape: 2 dim of b: 2
len of c.shape: 3 dim of c: 3


### `size`
Contains total number of elements in array.

In [26]:
print('total elements in a=', a.size)
print('total elements in b=', b.size)
print('total elements in c=', c.size)

total elements in a= 5
total elements in b= 10
total elements in c= 12


**product of elements in `ndarray.shape` is equals to `ndarray.size` or total elements**
`ndarray.shape` returns a tuple or a sequence of numbers

In [27]:
# numpy.prod() -> takes an array or a sequence of numbers as input and returns the product of all the elements in it.
# math.prod() can be used too to get the product.

import math

# prod_a_shape = np.prod(a.shape)
# prod_b_shape = np.prod(b.shape)
# prod_c_shape = np.prod(c.shape)

prod_a_shape = math.prod(a.shape)
prod_b_shape = math.prod(b.shape)
prod_c_shape = math.prod(c.shape)

print(a.size == prod_a_shape)
print(b.size == prod_b_shape)
print(c.size == prod_c_shape)

# array -> Shape -> Multiplication -> total element returned by ndarray.size
# a -> (5,) -> 5 -> 5
# b -> (2, 5) -> 2*5 -> 10
# c -> (2, 2, 3) -> 2*2*3 -> 12

True
True
True


### `dtype`
Contains the data type of the array.

In [28]:
a = np.arange(10, 21)
print(a, a.dtype)

b = np.linspace(10, 21, 5)
print(b, b.dtype)

text = ['numpy', 'is', 'fun']
c = np.array(text)
print(c, type(c), c.dtype)

[10 11 12 13 14 15 16 17 18 19 20] int64
[10.   12.75 15.5  18.25 21.  ] float64
['numpy' 'is' 'fun'] <class 'numpy.ndarray'> <U5


## Array Manipulation

### Sorting
using `np.sort()`

In [29]:
a = np.random.uniform(0, 100, 5)
print(a)
np.sort(a)

[15.48966293 65.2986112  85.19151234 84.54598672 58.74663433]


array([15.48966293, 58.74663433, 65.2986112 , 84.54598672, 85.19151234])

In [30]:
# Reverse the sorted array
np.flip(np.sort(a))

array([85.19151234, 84.54598672, 65.2986112 , 58.74663433, 15.48966293])

### Adding
using `np.concatenate()`

In [31]:
a = np.arange(10)
b = np.arange(10, 21)
c = np.concatenate((a, b))
c

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [32]:
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([[7, 8, 9], [10, 11, 12]])
c = np.concatenate((a, b), axis=1)
c

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

### Removing

**Removing Elements by Index**

In [33]:
a = np.arange(5)
print(a)
a = np.delete(a, 2)
print(a)

indices = [1, 3]
a = np.delete(a, indices)
print(a)

[0 1 2 3 4]
[0 1 3 4]
[0 3]


**Removing Elements that Match a Condition**

In [34]:
a = np.arange(0, 41, 2)
print(a)

a = a[a >= 20]
print(a)

a = a[a != 30]
print(a)

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40]
[20 22 24 26 28 30 32 34 36 38 40]
[20 22 24 26 28 32 34 36 38 40]


**Removing Elements Using List Comprehension**

In [35]:
a = np.arange(20, 61, 2)
print(a)
a = np.array([x for x in a if not x <= 40])
print(a)

[20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60]
[42 44 46 48 50 52 54 56 58 60]


## Reshaping Array

using `ndarray.reshape()`. Gives a new shape to an array without changing the data. 

In [36]:
a = np.arange(6)
print('a=', a)
print('shape:', a.shape)
print('dim:', a.ndim)

a= [0 1 2 3 4 5]
shape: (6,)
dim: 1


In [37]:
a = a.reshape(2, 3)
print('a=\n', a)
print('shape:', a.shape)
print('dim:', a.ndim)

a=
 [[0 1 2]
 [3 4 5]]
shape: (2, 3)
dim: 2


## Changing dimensions/Adding axis

### using `np.newaxis`
Increases the dimensions of array by one dimension.

In [38]:
a = np.arange(6).reshape(3, 2)
print(a)
print(a.shape)
print(a.ndim)

[[0 1]
 [2 3]
 [4 5]]
(3, 2)
2


In [39]:
# a2 = a[np.newaxis, :]
b = a[:, np.newaxis]
print(b)
print(b.shape)
print(b.ndim)

[[[0 1]]

 [[2 3]]

 [[4 5]]]
(3, 1, 2)
3


### using `np.expand_dims`
Expands an array by inserting a new axis at a specified position

In [40]:
a = np.arange(9).reshape(3, 3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [41]:
b = np.expand_dims(a, axis=2)
print(b)
print(b.shape)

[[[0]
  [1]
  [2]]

 [[3]
  [4]
  [5]]

 [[6]
  [7]
  [8]]]
(3, 3, 1)


## Indexing
NumPy arrays can be indexed in the same ways as Python lists.

In [42]:
arr = np.arange(10, 40, 3)
arr

array([10, 13, 16, 19, 22, 25, 28, 31, 34, 37])

In [43]:
arr[0], arr[3], arr[9]

(10, 19, 37)

In [44]:
arr = np.random.randint(0, 100, (3, 3))
arr, arr.ndim, arr.shape

(array([[59, 66, 40],
        [17, 34, 58],
        [ 9, 17, 66]]),
 2,
 (3, 3))

In [45]:
arr[0][2], [1, 1], [2, 2]

(40, [1, 1], [2, 2])

## Slicing
Slicing allows to extract a portion of a Numpy array.
`array[start:stop:step]`

In [46]:
arr = np.random.randint(0, 100, 10)
arr

array([30, 37, 40, 10, 93, 67, 16, 85, 67, 24])

In [47]:
arr[5:], arr[:5], arr[4:8], arr[:-1], arr[::2], arr[::-1], arr[2:7:2]

(array([67, 16, 85, 67, 24]),
 array([30, 37, 40, 10, 93]),
 array([93, 67, 16, 85]),
 array([30, 37, 40, 10, 93, 67, 16, 85, 67]),
 array([30, 40, 93, 16, 67]),
 array([24, 67, 85, 16, 67, 93, 10, 40, 37, 30]),
 array([40, 93, 16]))

In [48]:
# 2 dimensional array
arr = np.random.randint(0, 100, (3, 3))
arr

array([[ 3, 59, 53],
       [75, 25, 56],
       [56, 82, 35]])

In [49]:
arr[0:, 1:], arr[:, :1],arr[::2, ::2], 

(array([[59, 53],
        [25, 56],
        [82, 35]]),
 array([[ 3],
        [75],
        [56]]),
 array([[ 3, 53],
        [56, 35]]))

## Basic array operations

### Addition

In [50]:
a = np.random.uniform(0, 100, (3, 3))
a

array([[57.92822684,  2.28712737, 53.43706201],
       [29.2485526 , 81.68049825,  6.85943772],
       [57.76736357,  5.48484034, 93.34655636]])

In [51]:
a + 1

array([[58.92822684,  3.28712737, 54.43706201],
       [30.2485526 , 82.68049825,  7.85943772],
       [58.76736357,  6.48484034, 94.34655636]])

In [52]:
b = np.random.uniform(0, 100, (3, 3))
b

array([[43.24523852, 75.96317136,  9.92443007],
       [ 5.7147279 , 87.84391098, 56.13560707],
       [21.3074432 , 24.55784376, 74.62676129]])

In [53]:
a + b

array([[101.17346536,  78.25029873,  63.36149208],
       [ 34.96328051, 169.52440923,  62.99504479],
       [ 79.07480677,  30.0426841 , 167.97331765]])