# Numpy Basics

## Installing Numpy

In [1]:
# using pip3
! pip3 install numpy

## Importing Numpy

In [2]:
import numpy as np
print(np)

<module 'numpy' from '/opt/homebrew/anaconda3/lib/python3.11/site-packages/numpy/__init__.py'>


## Numpy Array Restrictions

- All elements of the array must be of the same type of data.
- Once created, the total size of the array can’t change.
- The shape must be “rectangular”, not “jagged”; e.g., each row of a two-dimensional array must have the same number of columns.

## Creating Numpy Arrays

In [3]:
# 1D Array
a = np.array([1, 2, 3])
print(a)
# 2D Array
b = np.array([[1, 2, 3], [4, 5, 6]])
print(b)
# 3D Array
c = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(c)

[1 2 3]
[[1 2 3]
 [4 5 6]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


### Creating Numpy Arrays with specific data types

In [4]:
a = np.array([1, 2, 3])
b = np.array([3.0, 4.0, 5.0])
print(a.dtype)
print(b.dtype)

int64
float64


In [5]:
a = np.array([1, 2, 3], dtype='int16')
print(a)
print(a.dtype)

[1 2 3]
int16


In [6]:
a = np.array([1, 2, 3], dtype='float32')
print(a)
print(a.dtype)

[1. 2. 3.]
float32


### Using `np.zeros()`
create an array filled with zeros.

In [7]:
a = np.zeros(10)
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [8]:
s = (3, 3)
b = np.zeros(s)
print(b)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


### Using `np.ones()`
create an array filled with ones.

In [9]:
a = np.ones(5)
print(a)
b = np.ones(3, dtype='int64')
print(b)

[1. 1. 1. 1. 1.]
[1 1 1]


In [10]:
a = np.ones((5, 5))
print(a)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [11]:
a = np.ones((3, 3)) * 5
print(a)

[[5. 5. 5.]
 [5. 5. 5.]
 [5. 5. 5.]]


### Using `np.empty()`

create an array of a specified shape without initializing its elements. Unlike `np.zeros()` which initializes all elements to zeros, `np.empty()` does not initialize the elements at all. Instead, it allocates the memory needed for the array but does not set the values of the elements. The values of the array will be whatever happens to already exist at that memory location.

In [12]:
a = np.empty(5)
print(a)

[1. 1. 1. 1. 1.]


In [13]:
b = np.empty((4, 4))
print(b)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


### Using `np.arange()`
create arrays with regularly spaced values within a specified interval. It is similar to Python's built-in `range()` function but returns an array instead of a list.

In [14]:
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [15]:
b = np.arange(10, 20)
print(b)

[10 11 12 13 14 15 16 17 18 19]


In [16]:
c = np.arange(30, 60, 2)
print(c)

[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58]


### Using `np.linspace()`
create arrays with evenly spaced numbers over a specified interval. Unlike `np.arange()`, which generates values with a specified step size, `np.linspace()` generates values that are evenly spaced between the specified start and stop values, inclusive by default.

In [17]:
a = np.linspace(10, 20)
print(a)

[10.         10.20408163 10.40816327 10.6122449  10.81632653 11.02040816
 11.2244898  11.42857143 11.63265306 11.83673469 12.04081633 12.24489796
 12.44897959 12.65306122 12.85714286 13.06122449 13.26530612 13.46938776
 13.67346939 13.87755102 14.08163265 14.28571429 14.48979592 14.69387755
 14.89795918 15.10204082 15.30612245 15.51020408 15.71428571 15.91836735
 16.12244898 16.32653061 16.53061224 16.73469388 16.93877551 17.14285714
 17.34693878 17.55102041 17.75510204 17.95918367 18.16326531 18.36734694
 18.57142857 18.7755102  18.97959184 19.18367347 19.3877551  19.59183673
 19.79591837 20.        ]


In [18]:
b = np.linspace(0, 100, num=10) # default num = 50
print(b)

[  0.          11.11111111  22.22222222  33.33333333  44.44444444
  55.55555556  66.66666667  77.77777778  88.88888889 100.        ]


In [19]:
c = np.linspace(10, 20, 5)
print(c)

[10.  12.5 15.  17.5 20. ]
